version: "3.2"
services:

  sql-server-db:
    container_name: mssql-server-container
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "2433:1433"
      - "2434:1434"
    environment:
      SA_PASSWORD: "PajaPatak123"
      ACCEPT_EULA: "Y"
      MSSQL_PID:   "Developer"